config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

urlpatterns = [
    path("", RedirectView.as_view(url="converter/"), name='home'),
    # Django Admin, {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("currency_exchange.users.urls", namespace="users")),
    # Converter App RLs
    path("converter/", include("currency_exchange.converter.urls", namespace="converter")),
    # Transfer App URLs
    path("transfer/", include("currency_exchange.transfer.urls", namespace="transfer")),
    # User account management
    path("accounts/", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # Allows the error pages to be debugged during development,
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

currency_exchange/converter/urls.py
from django.urls import path, re_path

from .views import converter_view

app_name = "converter"

urlpatterns = [
    path("", view=converter_view, name="index"),
]

currency_exchange/transfer/urls.py
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required

from currency_exchange.transfer.views import (
    wallet_view,
    account_update_view,
    money_transfer_view,
)

app_name = "transfer"

urlpatterns = [
    path("~wallet/<str:username>/", view=wallet_view, name="wallet"),
    path("~update/<str:username>/", view=account_update_view, name="update"),
    path("~transfer/<uuid:account_uuid>", view=money_transfer_view, name="transfer")
]

currency_exchange/users/urls.py
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required

from currency_exchange.users.views import(
    user_detail_view,
    user_redirect_view,
    user_update_view,
    register_profile,
    profile,
)

app_name = "users"

urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("~register-profile/", view=register_profile, name="register_profile"),
    path("~profile/<str:username>/", view=profile, name="profile"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

currency_exchange/converter/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Currency(models.Model):
    """Currency symbols available from the Open Exchange Rates API"""
    currency_symbol = models.CharField(_("Currency Symbol"),  max_length=4)
    currency_name = models.CharField(_("Name of Currency"), max_length=128)

    class Meta:
        verbose_name_plural = 'currencies'
        ordering = ('currency_name',)

    def __str__(self):
        return self.currency_name


class ConversionRate(models.Model):
    """Latest conversion rates from Open Exchange Rates endpoint"""
    symbol = models.OneToOneField(Currency, on_delete=models.CASCADE)
    rate = models.DecimalField(_("Conversion Rate - USD"), decimal_places=9, max_digits=20)

    class Meta:
        ordering = ('symbol',)

    def __str__(self):
        return str(self.symbol)

currency_exchange/converter/forms.py
from django import forms

from .models import Currency

query_set = Currency.objects.all()


class ConverterForm(forms.Form):
    """ Form for handling currency conversion """
    currency_from = forms.ModelChoiceField(queryset=query_set, empty_label="Currency to convert from")
    amount_from = forms.DecimalField(required=True, decimal_places=9, max_digits=20)
    currency_to = forms.ModelChoiceField(queryset=query_set, empty_label="Currency to convert to")

currency_exchange/transfer/forms.py
from django import forms
from django.contrib.auth import get_user_model

from .models import SentMoney


User = get_user_model()


class AccountUpdateForm(forms.Form):

    deposit = forms.DecimalField(required=True, decimal_places=9, max_digits=20)


class SentMoneyForm(forms.ModelForm):
    query_set = User.objects.all()
    transfer_to = forms.ModelChoiceField(queryset=query_set, empty_label="Person to receive money")
    credit = forms.DecimalField(required=True, decimal_places=9, max_digits=20)

    class Meta:

        model = SentMoney
        fields = ('transfer_to', 'credit', )

currency_exchange/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from django import forms

from allauth.account.forms import SignupForm

from currency_exchange.converter.models import Currency

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):

    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserProfileForm(forms.ModelForm):
    query_set = Currency.objects.all()
    picture = forms.ImageField(required=False)
    preferred_currency = forms.ModelChoiceField(queryset=query_set, required=True)

    class Meta:

        model = User
        fields = ('username', 'preferred_currency', 'picture', )


# UserSignupForm inherits from django-allauth's SignupForm
class UserSignupForm(SignupForm):
    # Query for all supported currencies
    query_set = Currency.objects.all()
    preferred_currency = forms.ModelChoiceField(queryset=query_set, required=True)
    picture = forms.ImageField(required=False)

    # Put in custom signup logic
    def custom_signup(self, request, user):

        # Set the user's type from the form response
        user.preferred_currency = self.cleaned_data["preferred_currency"]
        # Set the user's type from the form response
        user.picture = self.cleaned_data["picture"]

        # Save the user's picture and currency to their database record
        user.save()

currency_exchange/converter/views.py
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView

from .models import Currency
from .forms import ConverterForm
from .converter import ConverterMixin


class ConverterView(ConverterMixin, TemplateView, FormView):
    template_name = 'pages/home.html'
    form_class = ConverterForm

    def get_context_data(self, **kwargs):
        # Add a list of all currencies to render
        kwargs['currencies'] = Currency.objects.all()
        if 'form' not in kwargs:
            kwargs['form'] = self.get_form()
        return kwargs

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))

    def form_valid(self, form):
        return self.render_converter_response(self.get_context_data(form=form))

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


converter_view = ConverterView.as_view()

currency_exchange/transfer/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.http import HttpResponseRedirect
from django.utils.translation import gettext_lazy as _
from django.views.generic.base import TemplateView
from django.views.generic import FormView

from currency_exchange.converter.models import Currency, ConversionRate
from . models import Account, ReceivedMoney, SentMoney
from . forms import AccountUpdateForm, SentMoneyForm
from .transfer import account_deposit, money_transfer


User = get_user_model()


class WalletView(LoginRequiredMixin, TemplateView):

    template_name = 'pages/wallet.html'

    def get_context_data(self, username, **kwargs):
        # Create proxy object for the template context
        user = User.objects.get(username=username)
        preferred_currency = user.preferred_currency
        currency = Currency.objects.get(currency_name=preferred_currency)
        conversion = ConversionRate.objects.get(symbol=currency)
        account = Account.objects.get_or_create(username=user)[0]
        balance = account.balance
        rate = conversion.rate
        amount = balance*rate
        user_uuid = user.uuid
        money_sent = SentMoney.objects.filter(sender_uuid=user_uuid)
        money_received = ReceivedMoney.objects.filter(receiver_uuid=user_uuid)
        for money in money_sent:
            print(money.transfer_to)
            print(money.debit)
        for money in money_received:
            print(money.transfer_from)
            print(money.debit)
        kwargs['currency'] = currency
        kwargs['account'] = account
        kwargs['amount'] = amount
        kwargs['money_sent'] = money_sent
        kwargs['money_received'] = money_received
        return kwargs


wallet_view = WalletView.as_view()


class MoneyTransferView(LoginRequiredMixin, TemplateView, FormView):

    model = Account
    form_class = SentMoneyForm
    template_name = 'transfer/moneytransfer_form.html'

    def get_context_data(self, account_uuid, **kwargs):
        # Create proxy object for the template context
        account = Account.objects.get(account_number=account_uuid)
        user = account.username
        userprofile = UserProfile.objects.get(username=user)
        preferred_currency = userprofile.preferred_currency
        currency = Currency.objects.get(currency_name=preferred_currency)
        kwargs['username'] = user.username
        kwargs['currency'] = currency
        kwargs['userprofile'] = userprofile
        kwargs['account'] = account
        if 'form' not in kwargs:
            kwargs['form'] = self.get_form()
        return kwargs

    def form_invalid(self, account_uuid, form):
        return self.render_to_response(self.get_context_data(account_uuid, form=form))

    def form_valid(self, account_uuid, form):
        return self.render_to_response(self.get_context_data(account_uuid, form=form))

    def post(self, request, *args, **kwargs):
        user = self.request.user
        userprofile = UserProfile.objects.get(username=user)
        sender_uuid = userprofile.uuid
        sender_currency = userprofile.preferred_currency
        currency = Currency.objects.get(currency_name=sender_currency)
        conversion = ConversionRate.objects.get(symbol=currency)
        form = self.get_form()
        account_uuid = kwargs['account_uuid']
        account = Account.objects.get(account_number=account_uuid)
        balance = account.balance
        print(balance)
        if form.is_valid():
            sent_amount = form.cleaned_data['credit']
            if sent_amount > balance:
                raise ValidationError("Insufficient balance")
            receiverprofile = form.cleaned_data['transfer_to']
            context={}
            context['sender_uuid'] = sender_uuid
            context['sender_currency'] = currency.currency_name
            context['sender_rate'] = conversion.rate
            context['sent_amount'] = sent_amount
            context['account_uuid'] = account_uuid
            money_transfer(context, receiverprofile)
            return HttpResponseRedirect('/transfer/~wallet/{}/'.format(user.username))
        else:
            return self.form_invalid(account_uuid, form)


money_transfer_view = MoneyTransferView.as_view()


class AccountUpdateView(LoginRequiredMixin, TemplateView, FormView):

    model = Account
    form_class = AccountUpdateForm
    template_name = 'transfer/accountupdate_form.html'

    def get_context_data(self, username, **kwargs):
        # Create proxy object for the template context
        user = User.objects.get(username=username)
        userprofile = UserProfile.objects.get(username=user)
        preferred_currency = userprofile.preferred_currency
        currency = Currency.objects.get(currency_name=preferred_currency)
        account = Account.objects.get(username=user)
        kwargs['username'] = username
        kwargs['currency'] = currency
        kwargs['userprofile'] = userprofile
        kwargs['account'] = account
        if 'form' not in kwargs:
            kwargs['form'] = self.get_form()
        return kwargs

    def form_invalid(self, username, form):
        return self.render_to_response(self.get_context_data(username, form=form))

    def form_valid(self, username, form):
        return self.render_to_response(self.get_context_data(username, form=form))

    def post(self, request, *args, **kwargs):
        username = kwargs['username']
        form = self.get_form()
        if form.is_valid():
            deposit = form.cleaned_data['deposit']
            account_deposit(username, deposit)
            return HttpResponseRedirect('/transfer/~wallet/{}/'.format(username))
        else:
            return self.form_invalid(username, form)


account_update_view = AccountUpdateView.as_view()

currency_exchange/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView
from django.shortcuts import render, redirect

from allauth.account.views import SignupView

from currency_exchange.users.forms import UserProfileForm


User = get_user_model()


class ProfileSignupView(SignupView):

    def post(self, request, *args, **kwargs):
        """
        Handle Images in POST requests: instantiate a form instance including the passed
        POST image variable and then check if it's valid.
        """
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["username", "preferred_currency", "picture", ]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


@login_required
def profile(request, username):
    try:
        user = User.objects.get(username=username)
    except User.DoesNotExist:
        return redirect('index')

    form = UserProfileForm(
        {'username': user.username, 'picture': user.picture, 'preferred_currency': user.preferred_currency})

    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save(commit=True)
            return redirect('users:profile', user.username)
        else:
            print(form.errors)
    return render(request, 'pages/profile.html',
                  {user: 'user', 'username': username, 'form': form})


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()


class RegisterProfile(FormView):
    form_class = UserProfileForm
    template_name = "users/profile_registration.html"

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            user_profile = form.save(commit=False)
            user_profile.username = request.user
            user_profile.save()
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_success_url(self):
        username = self.request.user.username
        self.success_url = "/users/{}/".format(username)
        if self.success_url:
            url = self.success_url
        else:
            raise improperlyConfigured(
                "No URL to redirect to. Provide a success URL"
                )
        return url


register_profile = RegisterProfile.as_view()

currency_exchange/templates/pages/home.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Currency Converter{% endblock %}

{% block content %}
  <h1>Currency Converter</h1>
  <form class="form-horizontal" method="post" action="{% url 'converter:index' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Convert</button>
      </div>
    </div>
  </form>
</div>
{% if received_amount %}
  <center>
    <h1>
    {{sent_amount}} {{ sender_symbol }} is equivalent to <b>{{ received_amount }}</b> {{ receiver_symbol }}
    </h1>
  </center>
{% endif %}
{% endblock %}

currency_exchange/templates/pages/profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }} Profile{% endblock %}

{% block content %}
<h1>{{user.username}} Profile</h1>
<br />
<h2>Profile Picture: </h2>
<img src="{{ MEDIA_URL }}{{ user.picture }}" width="512"
    height="512" alt="Responsive image" class="img-thumbnail"/>
<br />
<p><strong>Preferred Currency:</strong> &nbsp; {{ user.preferred_currency }}</p>
<div>
    {% if user.username == request.user.username %}
      <br/>
      <h3> Edit Profile: </h3>
      <br/>
      <form class="form-horizontal" method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="control-group">
          <div class="controls">
            <button type="submit" class="btn btn-primary">Update Profile</button>
          </div>
        </div>
       </form>
    {% endif %}
</div>
{% endblock content %}

currency_exchange/templates/pages/profile_registration.html
{% block title %}User Profile Registration{% endblock %}
{% load crispy_forms_tags %}

{% block content %}
  <h1>Hi Registration - Step 2</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:register_profile' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}

currency_exchange/templates/pages/wallet.html
{% extends "base.html" %}

{% block title %}{{ user.username }} Wallet {% endblock %}

{% block content %}
<figure class="text-center">
  <blockquote class="blockquote">
    <p class="h2"> Money Transfer Wallet </p>
  </blockquote>
  <figcaption class="blockquote-footer">
    <p class="h7">Transfer money to and from different currencies worldwide</p>
  </figcaption>
</figure>
<br />
<br />
<center>
  <div class="container">
    <div class="row">
      <div class="col align-self-center">
        <p class="text-capitalize h3">Hi {{ user.username }} </p>
        <figure class="figure">
          <img src="{{ MEDIA_URL }}{{ user.picture }}" class="figure-img img-fluid rounded-circle"
            width="150" alt="{{ user.preferred_currency }}">
          <figcaption class="figure-caption"><p class="h7">Currency:&nbsp;{{user.preferred_currency}}<br/>
            Available Balance: {{ amount }}&nbsp;&nbsp; {{ currency.currency_symbol }}<p></figcaption>
        </figure>
      </div>
      <div class="col align-self-center">
       <a class="btn btn-outline-success" data-mdb-ripple-color="dark"
        href="{% url 'transfer:update' request.user.username %}" role="button">Deposit Money</a>
      </div>
      <div class="col align-self-center">
        <a class="btn btn-outline-info" data-mdb-ripple-color="dark"
           href="{% url 'transfer:transfer' account.account_number %}" role="button">Send Money</a>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col align-self-start">
        {% if money_sent %}
        <table class="table table-hover">
          <caption>Money Sent</caption>
          <thead class="thead-light">
            <tr>
              <th scope="col">Date</th>
              <th scope="col">Sent To</th>
              <th scope="col">Amount</th>
            </tr>
          </thead>
          <tbody>
            {% for money in money_sent %}
            <tr>
              <th scope="row">{{ money.date }}</th>
              <td>{{ money.transfer_to }}</td>
              <td>{{ money.credit }} {{ money.currency }}</td>
            </tr>
            {% endfor %}
          </tbody>
          {% endif %}
        </table>
     </div>
      <div class="col align-self-start">
        {% if money_received %}
        <table class="table table-hover">
          <caption>Money Received</caption>
          <thead class="thead-light">
            <tr>
              <th scope="col">Date</th>
              <th scope="col">Received From</th>
              <th scope="col">Amount</th>
            </tr>
          </thead>
          <tbody>
            {% for money in money_received %}
            <tr>
              <th scope="row">{{ money.date }}</th>
              <td>{{ money.transfer_from }}</td>
              <td>{{ money.debit }} {{ money.currency }}</td>
            </tr>
            {% endfor %}
          </tbody>
          {% endif %}
        </table>
     </div>

    </div>
  </div>
 </center>
{% endblock content %}